dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install . #install the current version of the code
  - pip install -r requirements.txt
  - npm install -g jsdoc
addons:
  apt_packages:
    - pandoc # required for docs
# command to run tests
script:
  - pytest
  # - python tests/wiggum_test_script.py
  # Use Sphinx to make the html docs
  - cd docs
  - make html # must be run in the docs folder
# save info to speed up builds
cache: pip
# Tell Travis CI to deply the documentation by copying the documentation to the
# gh-pages branch of your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true # requires to prevent travis from deleting the built website
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: docs/html/ # where compiled docs are placed by sphinx, set in sphinx conf.py
  target_branch: gh-pages

notifications:
  slack:
    rooms: oudalab:hYEt5Sslpd5gb7aMfQeI6EoM#code
